# BIEN 514 Homework 3

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [3]:
data_0p5 = pd.read_csv('Walk_0p5micron.csv')

square displacement = $(x_1-x_0)^2 + (y_1-y_0)^2$

In [6]:
data_0p5

,t,x,y,x.1,y.1,x.2,y.2,x.3,y.3,x.4,...,x.95,y.95,x.96,y.96,x.97,y.97,x.98,y.98,x.99,y.99
0,0.000000,0.00000,0.00000,0.000000,0.00000,0.00000,0.000000,0.00000,0.00000,0.000000,...,0.000000,0.00000,0.00000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
1,0.033333,-0.20608,-0.20100,0.230590,0.23350,0.38159,0.046708,0.17719,-0.16880,0.066875,...,0.183600,0.19390,0.26441,-0.02903,0.011367,-0.093451,0.127430,0.37736,0.236220,0.081774
2,0.066667,0.40363,0.22766,-0.071676,0.51141,0.36233,0.154320,0.16389,-0.30742,-0.206180,...,0.087922,-0.11169,-0.19842,-0.13242,0.227800,-0.226570,0.026205,0.18493,0.025101,-0.186780
3,0.100000,0.73032,0.27732,-0.243010,0.35566,-0.14850,0.479560,0.12477,-0.54321,0.373850,...,-0.222960,-0.14576,-0.13920,-0.19242,0.346440,-0.350520,0.214770,0.52189,0.181310,0.084366
4,0.133330,0.66101,0.40023,-0.537420,0.17883,-0.35128,0.358810,0.28202,-0.87144,0.750450,...,-0.219880,-0.49250,0.13111,-0.16414,0.352870,0.168440,0.373510,0.38140,0.700350,0.184940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,9.866700,4.30800,1.52490,-2.563500,3.48120,3.85320,-0.664720,-6.19440,-7.85830,1.182900,...,-0.386380,2.40210,0.30244,-4.91860,1.878400,2.921100,-2.262200,12.06100,2.473900,0.760970
297,9.900000,4.09910,1.53660,-2.284600,3.57710,3.97640,-0.711920,-6.30540,-7.82470,1.281400,...,-0.433610,2.36920,0.39653,-5.04050,2.177800,2.576300,-2.639900,11.74600,2.337400,0.735580
298,9.933300,3.67650,1.46320,-2.271300,3.31960,3.98430,-0.972490,-6.61180,-7.67840,0.408450,...,0.094318,2.25710,0.40390,-5.70460,1.843500,2.802300,-2.710500,11.85400,2.087100,0.587120
299,9.966700,3.45490,1.32400,-3.262100,3.26390,4.13730,-1.005000,-6.56050,-7.62350,0.465480,...,-0.077154,2.09240,0.45940,-5.53900,1.878000,2.870800,-3.086000,11.81500,1.949500,0.825920
300,10.000000,3.15820,0.78396,-3.294800,2.80590,4.08650,-1.109900,-6.46570,-7.32350,0.422250,...,0.026944,2.30440,0.29875,-5.07540,2.058700,3.092800,-3.097700,12.11700,1.764300,1.007700

In [5]:
time = data_0p5[['t']]
steps = data_0p5.drop('t', axis=1)

In [24]:
test = steps.iloc[:, :] #.diff().pow(2).drop(0)

In [25]:
test[1:].reset_index(drop=True) - test[:-1]

,x,y,x.1,y.1,x.2,y.2,x.3,y.3,x.4,y.4,...,x.95,y.95,x.96,y.96,x.97,y.97,x.98,y.98,x.99,y.99
0,-0.20608,-0.20100,0.230590,0.23350,0.38159,0.046708,0.17719,-0.16880,0.066875,-0.11538,...,0.183600,0.19390,0.26441,-0.029030,0.011367,-0.093451,0.127430,0.37736,0.236220,0.081774
1,0.60971,0.42866,-0.302266,0.27791,-0.01926,0.107612,-0.01330,-0.13862,-0.273055,-0.57152,...,-0.095678,-0.30559,-0.46283,-0.103390,0.216433,-0.133119,-0.101225,-0.19243,-0.211119,-0.268554
2,0.32669,0.04966,-0.171334,-0.15575,-0.51083,0.325240,-0.03912,-0.23579,0.580030,0.18414,...,-0.310882,-0.03407,0.05922,-0.060000,0.118640,-0.123950,0.188565,0.33696,0.156209,0.271146
3,-0.06931,0.12291,-0.294410,-0.17683,-0.20278,-0.120750,0.15725,-0.32823,0.376600,0.22481,...,0.003080,-0.34674,0.27031,0.028280,0.006430,0.518960,0.158740,-0.14049,0.519040,0.100574
4,0.04802,-0.11210,0.183020,-0.68386,-0.04855,0.109390,-0.14637,-0.38176,0.165900,-0.29731,...,-0.072330,0.06801,-0.15927,0.094065,-0.238260,0.154550,-0.099670,-0.01194,0.221140,0.008160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,0.40520,0.38300,0.135800,0.07710,0.03350,0.390980,-0.46670,-0.29690,0.269980,-0.20790,...,0.038660,-0.39220,0.53842,0.014800,0.009800,-0.326700,-0.047800,-0.22900,-0.503300,-0.084400
296,-0.20890,0.01170,0.278900,0.09590,0.12320,-0.047200,-0.11100,0.03360,0.098500,-0.12750,...,-0.047230,-0.03290,0.09409,-0.121900,0.299400,-0.344800,-0.377700,-0.31500,-0.136500,-0.025390
297,-0.42260,-0.07340,0.013300,-0.25750,0.00790,-0.260570,-0.30640,0.14630,-0.872950,-0.39530,...,0.527928,-0.11210,0.00737,-0.664100,-0.334300,0.226000,-0.070600,0.10800,-0.250300,-0.148460
298,-0.22160,-0.13920,-0.990800,-0.05570,0.15300,-0.032510,0.05130,0.05490,0.057030,-0.05870,...,-0.171472,-0.16470,0.05550,0.165600,0.034500,0.068500,-0.375500,-0.03900,-0.137600,0.238800
299,-0.29670,-0.54004,-0.032700,-0.45800,-0.05080,-0.104900,0.09480,0.30000,-0.043230,-0.00680,...,0.104098,0.21200,-0.16065,0.463600,0.180700,0.222000,-0.011700,0.30200,-0.185200,0.181780

In [27]:
test

,x,y,x.1,y.1,x.2,y.2,x.3,y.3,x.4,y.4,...,x.95,y.95,x.96,y.96,x.97,y.97,x.98,y.98,x.99,y.99
0,0.00000,0.00000,0.000000,0.00000,0.00000,0.000000,0.00000,0.00000,0.000000,0.00000,...,0.000000,0.00000,0.00000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
1,-0.20608,-0.20100,0.230590,0.23350,0.38159,0.046708,0.17719,-0.16880,0.066875,-0.11538,...,0.183600,0.19390,0.26441,-0.02903,0.011367,-0.093451,0.127430,0.37736,0.236220,0.081774
2,0.40363,0.22766,-0.071676,0.51141,0.36233,0.154320,0.16389,-0.30742,-0.206180,-0.68690,...,0.087922,-0.11169,-0.19842,-0.13242,0.227800,-0.226570,0.026205,0.18493,0.025101,-0.186780
3,0.73032,0.27732,-0.243010,0.35566,-0.14850,0.479560,0.12477,-0.54321,0.373850,-0.50276,...,-0.222960,-0.14576,-0.13920,-0.19242,0.346440,-0.350520,0.214770,0.52189,0.181310,0.084366
4,0.66101,0.40023,-0.537420,0.17883,-0.35128,0.358810,0.28202,-0.87144,0.750450,-0.27795,...,-0.219880,-0.49250,0.13111,-0.16414,0.352870,0.168440,0.373510,0.38140,0.700350,0.184940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,4.30800,1.52490,-2.563500,3.48120,3.85320,-0.664720,-6.19440,-7.85830,1.182900,-2.00970,...,-0.386380,2.40210,0.30244,-4.91860,1.878400,2.921100,-2.262200,12.06100,2.473900,0.760970
297,4.09910,1.53660,-2.284600,3.57710,3.97640,-0.711920,-6.30540,-7.82470,1.281400,-2.13720,...,-0.433610,2.36920,0.39653,-5.04050,2.177800,2.576300,-2.639900,11.74600,2.337400,0.735580
298,3.67650,1.46320,-2.271300,3.31960,3.98430,-0.972490,-6.61180,-7.67840,0.408450,-2.53250,...,0.094318,2.25710,0.40390,-5.70460,1.843500,2.802300,-2.710500,11.85400,2.087100,0.587120
299,3.45490,1.32400,-3.262100,3.26390,4.13730,-1.005000,-6.56050,-7.62350,0.465480,-2.59120,...,-0.077154,2.09240,0.45940,-5.53900,1.878000,2.870800,-3.086000,11.81500,1.949500,0.825920
300,3.15820,0.78396,-3.294800,2.80590,4.08650,-1.109900,-6.46570,-7.32350,0.422250,-2.59800,...,0.026944,2.30440,0.29875,-5.07540,2.058700,3.092800,-3.097700,12.11700,1.764300,1.007700

In [30]:
test[3:].reset_index(drop=True) - test[:-3]

,x,y,x.1,y.1,x.2,y.2,x.3,y.3,x.4,y.4,...,x.95,y.95,x.96,y.96,x.97,y.97,x.98,y.98,x.99,y.99
0,0.73032,0.277320,-0.243010,0.35566,-0.14850,0.479560,0.12477,-0.54321,0.373850,-0.50276,...,-0.222960,-0.14576,-0.139200,-0.192420,0.346440,-0.350520,0.214770,0.521890,0.181310,0.084366
1,0.86709,0.601230,-0.768010,-0.05467,-0.73287,0.312102,0.10483,-0.70264,0.683575,-0.16257,...,-0.403480,-0.68640,-0.133300,-0.135110,0.341503,0.261891,0.246080,0.004040,0.464130,0.103166
2,0.30540,0.060470,-0.282724,-1.01644,-0.76216,0.313880,-0.02824,-0.94578,1.122530,0.11164,...,-0.380132,-0.31280,0.170260,0.062345,-0.113190,0.549560,0.247635,0.184530,0.896389,0.379880
3,-0.13915,0.043330,-0.045240,-0.77592,-0.39409,-0.249710,0.25359,-0.81299,0.606560,-0.56534,...,0.286218,-0.57417,0.014130,0.378930,-0.358224,1.128250,-0.094650,-0.166420,0.424810,0.292254
4,-0.22105,-0.339707,-0.050200,-0.68722,-0.19400,0.107080,-0.11148,-0.77526,0.329550,-0.91595,...,0.571890,-0.41708,-0.300670,0.348710,-0.323841,0.814610,-0.333132,-0.301223,-0.007940,0.421990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,0.20240,0.458500,-0.254200,-0.07650,-0.14490,-0.361320,-1.06110,-0.83540,0.405640,-0.50910,...,-0.043180,-0.11570,0.254495,-0.267300,0.507000,-0.741100,0.042200,0.298000,-0.457100,-0.332630
294,0.06080,0.392200,0.074600,-0.24740,0.61810,-0.198180,-0.69590,-0.68200,0.326480,-0.11410,...,-0.128770,-0.23840,0.400813,-0.095400,0.557200,-0.818500,-0.623100,-0.487000,-0.609600,-0.149510
295,-0.22630,0.321300,0.428000,-0.08450,0.16460,0.083210,-0.88410,-0.11700,-0.504470,-0.73070,...,0.519358,-0.53720,0.639880,-0.771200,-0.025100,-0.445500,-0.496100,-0.436000,-0.890100,-0.258250
296,-0.85310,-0.200900,-0.698600,-0.21730,0.28410,-0.340280,-0.36610,0.23480,-0.717420,-0.58150,...,0.309226,-0.30970,0.156960,-0.620400,-0.000400,-0.050300,-0.823800,-0.246000,-0.524400,0.064950
297,-0.94090,-0.752640,-1.010200,-0.77120,0.11010,-0.397980,-0.16030,0.50120,-0.859150,-0.46080,...,0.460554,-0.06480,-0.097780,-0.034900,-0.119100,0.516500,-0.457800,0.371000,-0.573100,0.272120

In [ ]:
def msd(data):
    """
    calculate msd for each particle in 2D

    Parameters
    ----------
        data: random walk data
    """

    time = data['t']

    for time